//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocsManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agreement
    {
        public int RegistrationNomer { get; set; }
        public System.DateTime RegistrationData { get; set; }
        public string TypeDocument { get; set; }
        public string StateDocument { get; set; }
        public string TypeAgreement { get; set; }
        public System.DateTime DeadlineAgreement { get; set; }
        public string Conractor { get; set; }
        public decimal Amount { get; set; }
        public string CreatedUser { get; set; }
        public string SignedUser { get; set; }
        public Nullable<int> NumberSheets { get; set; }
        public string Summary { get; set; }
        public string FileName { get; set; }
        public string FileType { get; set; }
        public byte[] FileContent { get; set; }
    }
}
